const KEY='quantumflow-v1';
const quotesFallback=['Consistency is a superpower when you practice it every day.','Small progress every day adds up to remarkable results.','Do the next useful thing.','Your future is built from ordinary days used well.','Focus on the process. Let the progress follow.','You do not need a perfect day. You need a meaningful one.'];
let state={tab:'home',habits:[],study:[],goals:[],quote:0,quotes:[],loading:true,error:null};
let currentUser=null,timer=null,secs=1500;
const today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const withTimeout=(promise,ms=8000)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Request timed out. Please check your internet connection and Supabase project.')),ms))]);
function toast(m){const e=document.getElementById('toast');if(!e)return;e.textContent=m;e.className='toast show';setTimeout(()=>e.className='toast',2200)}
function auth(){return `<div class="wrap auth"><div class="card hero"><div class="brand">QuantumFlow</div><h1>Build better days.</h1><p class="muted">Track habits, study, goals and progress in one place.</p><input id="email" class="input" type="email" autocomplete="email" placeholder="Email"><input id="password" class="input" type="password" autocomplete="current-password" placeholder="Password"><div class="actions"><button class="btn" onclick="signIn()">Sign in</button><button class="btn secondary" onclick="signUp()">Create account</button></div><p class="muted small">Your personal data is protected by Supabase Row Level Security.</p></div></div>`}
function errorView(){return `<div class="wrap"><div class="card hero"><div class="brand">QuantumFlow</div><h2>Couldn't sync your data</h2><p class="muted">${esc(state.error||'Something went wrong while connecting to Supabase.')}</p><div class="actions"><button class="btn" onclick="bootstrap()">Retry</button><button class="btn secondary" onclick="clearAndRetry()">Reload</button></div><p class="muted small">If this keeps happening, check that your phone is online and the Supabase project is active.</p></div></div>`}
async function signIn(){const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;if(!email||!password)return toast('Enter email and password');const {error}=await withTimeout(supabaseClient.auth.signInWithPassword({email,password}));if(error)return toast(error.message);await bootstrap()}
async function signUp(){const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;if(password.length<6)return toast('Password must be at least 6 characters');const {data,error}=await withTimeout(supabaseClient.auth.signUp({email,password}));if(error)return toast(error.message);if(data.session)await bootstrap();else toast('Account created. Check your email if confirmation is enabled.')}
async function signOut(){await supabaseClient.auth.signOut();currentUser=null;state={tab:'home',habits:[],study:[],goals:[],quote:0,quotes:[],loading:false,error:null};render()}
async function clearAndRetry(){state.error=null;state.loading=true;render();await bootstrap()}
async function bootstrap(){state.error=null;state.loading=true;render();try{const {data:{session}}=await withTimeout(supabaseClient.auth.getSession());currentUser=session?.user||null;if(!currentUser){state.loading=false;render();return}await loadData();render()}catch(e){console.error(e);currentUser=null;state.loading=false;state.error=e?.message||'Unable to connect to Supabase.';render()}}
async function loadData(){const uid=currentUser.id;const results=await withTimeout(Promise.all([
 supabaseClient.from('habits').select('*').eq('user_id',uid).eq('is_active',true).order('created_at'),
 supabaseClient.from('study_sessions').select('*').eq('user_id',uid).order('started_at',{ascending:false}),
 supabaseClient.from('goals').select('*, goal_milestones(*)').eq('user_id',uid).order('created_at'),
 supabaseClient.from('habit_completions').select('habit_id,completed_on').eq('user_id',uid),
 supabaseClient.from('quotes').select('text,author,category').eq('is_active',true)
 ]),10000);const [h,s,g,m,q]=results;const firstError=[h,s,g,m,q].find(x=>x.error);if(firstError)throw new Error(firstError.error.message);const completions=m.data||[];state.habits=(h.data||[]).map(x=>({...x,days:completions.filter(c=>c.habit_id===x.id).map(c=>c.completed_on)}));state.study=s.data||[];state.goals=(g.data||[]).map(x=>({...x,name:x.title,milestones:(x.goal_milestones||[]).sort((a,b)=>a.sort_order-b.sort_order)}));state.quotes=q.data||[];state.quote=state.quotes.length?Math.floor(Math.random()*state.quotes.length):0;state.loading=false}
function done(h){return h.days.includes(today())}
function streak(h){let d=new Date(),n=0;for(;;){const s=d.toISOString().slice(0,10);if(!h.days.includes(s))break;n++;d.setDate(d.getDate()-1)}return n}
function bestStreak(h){const days=[...new Set(h.days)].sort();let best=0,run=0,prev=null;for(const s of days){const d=new Date(s+'T00:00:00');if(prev&&((d-prev)/86400000===1))run++;else run=1;best=Math.max(best,run);prev=d}return best}
function totalStudy(){return state.study.reduce((a,s)=>a+(Number(s.duration_minutes)||0),0)}
function score(){return Math.round(state.habits.reduce((a,h)=>a+(done(h)?1:0),0)/Math.max(1,state.habits.length)*100)}
function quoteText(){const q=state.quotes[state.quote];return q?`“${esc(q.text)}”${q.author?` — ${esc(q.author)}`:''}`:`“${quotesFallback[state.quote%quotesFallback.length]}”`}
function shell(content,title){return `<div class="wrap"><div class="top"><div><div class="brand">QuantumFlow</div><div class="muted">${esc(title||new Date().toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'}))}</div></div><button class="btn secondary" onclick="signOut()">Sign out</button></div>${content}</div>`}
function home(){return shell(`<div class="card hero"><div class="muted">TODAY'S QUOTE</div><p class="quote">${quoteText()}</p><button class="btn secondary" onclick="newQuote()">✦ New quote</button></div><div class="grid"><div class="card metric"><div class="muted">Today's score</div><strong>${score()}</strong><span class="muted">out of 100</span></div><div class="card metric"><div class="muted">Study time</div><strong>${(totalStudy()/60).toFixed(1)}h</strong><span class="muted">recorded</span></div></div><div class="card"><div class="row between"><h3>Today's Habits</h3><button class="btn secondary" onclick="addHabit()">+ Add</button></div><div class="list">${state.habits.length?state.habits.map(h=>habitRow(h)).join(''):'<p class="muted">Create your first habit.</p>'}</div></div><div class="card"><div class="row between"><h3>Quick Focus</h3><button class="btn" onclick="focusTimer()">Start 25m</button></div><p class="muted">Complete a focused study session and save it to your history.</p></div></div>`)}
function habitRow(h){return `<div class="item"><button class="check ${done(h)?'done':''}" onclick="toggleHabit('${h.id}')">${done(h)?'✓':''}</button><div class="grow"><b>${esc(h.name)}</b><div class="muted">🔥 ${streak(h)} day streak · ${h.days.length} completions</div></div><span class="pill">${done(h)?'Done':'Today'}</span></div>`}
function habits(){return shell(`<div class="top"><div><h2>My Habits</h2><div class="muted">Build consistency one day at a time.</div></div><button class="btn" onclick="addHabit()">+ Habit</button></div>${state.habits.map(h=>`<div class="card">${habitRow(h)}<div style="margin-top:12px" class="bar"><i style="width:${Math.min(100,h.days.length*3)}%"></i></div><div class="muted" style="margin-top:8px">Current ${streak(h)} · Best ${bestStreak(h)}</div></div>`).join('')}</div>`)}
function study(){return shell(`<div class="top"><div><h2>Study</h2><div class="muted">Plan and record focused work.</div></div><button class="btn" onclick="addStudy()">+ Session</button></div><div class="grid"><div class="card metric"><div class="muted">Total time</div><strong>${Math.round(totalStudy())}m</strong></div><div class="card metric"><div class="muted">Sessions</div><strong>${state.study.length}</strong></div></div><div class="card"><h3>Sessions</h3><div class="list">${state.study.length?state.study.map(s=>`<div class="item"><div class="grow"><b>${esc(s.title)}</b><div class="muted">${s.started_at?new Date(s.started_at).toLocaleDateString():'Today'} · ${s.duration_minutes} min</div></div><span class="pill green">${s.completed?'completed':'planned'}</span></div>`).join(''):'<p class="muted">No study sessions yet.</p>'}</div></div><div class="card"><h3>Focus Timer</h3><div class="timer" id="timer">${fmtTimer()}</div><div class="actions"><button class="btn" onclick="startTimer()">Start</button><button class="btn secondary" onclick="resetTimer()">Reset</button></div></div></div>`)}
function progress(){const completed=state.habits.reduce((a,h)=>a+h.days.length,0);return shell(`<h2>Progress</h2><div class="muted">Your real cloud-saved consistency.</div><div class="grid"><div class="card metric"><strong>${completed}</strong><span class="muted">Habit completions</span></div><div class="card metric"><strong>${score()}%</strong><span class="muted">Today's consistency</span></div><div class="card metric"><strong>${Math.max(0,...state.habits.map(h=>h.days.length),0)}</strong><span class="muted">Top habit completions</span></div><div class="card metric"><strong>${totalStudy()}m</strong><span class="muted">Study time</span></div></div><div class="card"><h3>Habit consistency</h3><div class="heat">${Array.from({length:140},(_,i)=>`<i class="${i%9===0||i%13===0?'on':''}"></i>`).join('')}</div></div></div>`)}
function goals(){return shell(`<div class="top"><div><h2>Goals</h2><div class="muted">Long-term progress powered by daily action.</div></div><button class="btn" onclick="addGoal()">+ Goal</button></div>${state.goals.map(g=>`<div class="card"><div class="row between"><h3>${esc(g.name)}</h3><b>${g.progress}%</b></div><div class="bar"><i style="width:${g.progress}%"></i></div><div class="muted" style="margin-top:10px">${g.milestones.length} milestones</div><div class="actions" style="margin-top:12px"><button class="btn secondary" onclick="advanceGoal('${g.id}',${g.progress})">Update progress</button></div></div>`).join('')}</div>`)}
function render(){const app=document.getElementById('app');if(!app)return;if(state.loading){app.innerHTML='<div class="wrap"><div class="card"><h2>Loading QuantumFlow…</h2><p class="muted">Syncing your data.</p></div></div>';document.getElementById('nav').innerHTML='';return}if(state.error){app.innerHTML=errorView();document.getElementById('nav').innerHTML='';return}if(!currentUser){app.innerHTML=auth();document.getElementById('nav').innerHTML='';return}const views={home,habits,study,progress,goals};app.innerHTML=views[state.tab]();document.getElementById('nav').className='nav';document.getElementById('nav').innerHTML=[['home','⌂','Home'],['habits','✓','Habits'],['study','▣','Study'],['progress','◒','Progress'],['goals','◆','Goals']].map(x=>`<button class="${state.tab===x[0]?'active':''}" onclick="state.tab='${x[0]}';render()"><b>${x[1]}</b>${x[2]}</button>`).join('')}
async function newQuote(){if(state.quotes.length){state.quote=(state.quote+1)%state.quotes.length;render()}else{state.quote=(state.quote+1)%quotesFallback.length;render()}toast('New quote ✦')}
async function addHabit(){const n=prompt('Habit name');if(!n?.trim())return;const {data,error}=await withTimeout(supabaseClient.from('habits').insert({user_id:currentUser.id,name:n.trim()}).select().single());if(error)return toast(error.message);state.habits.push({...data,days:[]});render();toast('Habit created')}
async function toggleHabit(id){const h=state.habits.find(x=>x.id===id);if(!h)return;const d=today();if(done(h)){const {error}=await withTimeout(supabaseClient.from('habit_completions').delete().eq('habit_id',id).eq('completed_on',d).eq('user_id',currentUser.id));if(error)return toast(error.message);h.days=h.days.filter(x=>x!==d);toast('Habit unchecked')}else{const {error}=await withTimeout(supabaseClient.from('habit_completions').insert({habit_id:id,user_id:currentUser.id,completed_on:d}));if(error)return toast(error.message);h.days.push(d);toast('Habit completed ✓')}render()}
async function addStudy(){const n=prompt('Study session name');if(!n?.trim())return;const d=Number(prompt('Duration in minutes','30'));if(!Number.isFinite(d)||d<=0)return;const {data,error}=await withTimeout(supabaseClient.from('study_sessions').insert({user_id:currentUser.id,title:n.trim(),started_at:new Date().toISOString(),ended_at:new Date().toISOString(),duration_minutes:d,completed:true}).select().single());if(error)return toast(error.message);state.study.unshift(data);render();toast('Study session saved')}
async function addGoal(){const n=prompt('Goal name');if(!n?.trim())return;const {data,error}=await withTimeout(supabaseClient.from('goals').insert({user_id:currentUser.id,title:n.trim(),progress:0}).select().single());if(error)return toast(error.message);const {data:milestone}=await withTimeout(supabaseClient.from('goal_milestones').insert({goal_id:data.id,user_id:currentUser.id,title:'First milestone',sort_order:0}).select().single());state.goals.push({...data,name:data.title,milestones:milestone?[milestone]:[]});render();toast('Goal created')}
async function advanceGoal(id,current){const next=Math.min(100,current+10);const {error}=await withTimeout(supabaseClient.from('goals').update({progress:next,is_completed:next===100,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',currentUser.id));if(error)return toast(error.message);const g=state.goals.find(x=>x.id===id);if(g)g.progress=next;render();toast('Goal updated')}
function fmtTimer(){return `${String(Math.floor(secs/60)).padStart(2,'0')}:${String(secs%60).padStart(2,'0')}`}
function startTimer(){if(timer)return;timer=setInterval(()=>{secs--;updateTimer();if(secs<=0){clearInterval(timer);timer=null;saveFocusSession()}},1000);toast('Focus started')}
async function saveFocusSession(){const {data,error}=await withTimeout(supabaseClient.from('study_sessions').insert({user_id:currentUser.id,title:'Focus Session',started_at:new Date(Date.now()-1500000).toISOString(),ended_at:new Date().toISOString(),duration_minutes:25,completed:true}).select().single());if(!error)state.study.unshift(data);saveTimerState();toast(error?'Focus finished, but could not sync':'Focus session complete 🎉');render()}
function resetTimer(){clearInterval(timer);timer=null;secs=1500;updateTimer()}
function updateTimer(){const e=document.getElementById('timer');if(e)e.textContent=fmtTimer()}
function focusTimer(){state.tab='study';render()}
function saveTimerState(){try{localStorage.setItem(KEY,JSON.stringify({secs}))}catch(_){} }
supabaseClient.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'){currentUser=null;state.error=null;state.loading=false;render()}else if(session&&!currentUser){currentUser=session.user;loadData().then(()=>{state.error=null;render()}).catch(e=>{state.loading=false;state.error=e?.message||'Unable to sync data.';render()})}});
bootstrap();