const KEY='quantumflow-v2';
const quotesFallback=['Consistency is a superpower when you practice it every day.','Small progress every day adds up to remarkable results.','Do the next useful thing.','Your future is built from ordinary days used well.','Focus on the process. Let the progress follow.','You do not need a perfect day. You need a meaningful one.'];
let state={tab:'home',habits:[],study:[],goals:[],quote:0,quotes:[],profile:null,leaderboard:[],loading:true,error:null};
let currentUser=null,timer=null,secs=Number(localStorage.getItem('qf-focus-secs')||1500),timerTotal=secs,timerStartedAt=null;
const today=()=>new Date().toISOString().slice(0,10);
const esc=s=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const withTimeout=(promise,ms=10000)=>Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Request timed out. Please check your internet connection.')),ms))]);
function toast(m){const e=document.getElementById('toast');if(!e)return;e.textContent=m;e.className='toast show';setTimeout(()=>e.className='toast',3200)}
function auth(){return `<div class="wrap auth"><div class="card hero"><div class="brand">QuantumFlow</div><h1>Build better days.</h1><p class="muted">Track habits, study, goals and progress in one place.</p><input id="email" class="input" type="email" autocomplete="email" placeholder="Email"><input id="password" class="input" type="password" autocomplete="new-password" placeholder="Password (6+ characters)"><div class="actions"><button class="btn" onclick="signIn()">Sign in</button><button class="btn secondary" onclick="signUp()">Create account</button></div><p id="authStatus" class="muted small"></p><p class="muted small">If email confirmation is enabled, confirm your email before signing in.</p></div></div>`}
function authError(error){const m=(error?.message||'').toLowerCase();if(m.includes('rate limit'))return 'Email sending limit reached. Wait and try again, or use an existing account.';if(m.includes('already registered')||m.includes('already exists'))return 'An account with this email already exists. Try Sign in.';return error?.message||'Could not complete authentication.'}
function errorView(){return `<div class="wrap"><div class="card hero"><div class="brand">QuantumFlow</div><h2>Couldn’t sync your data</h2><p class="muted">${esc(state.error||'Something went wrong while connecting to Supabase.')}</p><div class="actions"><button class="btn" onclick="bootstrap()">Retry</button><button class="btn secondary" onclick="location.reload()">Reload</button></div></div></div>`}
async function signIn(){const email=document.getElementById('email')?.value.trim().toLowerCase(),password=document.getElementById('password')?.value;if(!email||!password)return toast('Enter email and password');const {error}=await withTimeout(supabaseClient.auth.signInWithPassword({email,password}));if(error)return toast(authError(error));await bootstrap()}
async function signUp(){const email=document.getElementById('email')?.value.trim().toLowerCase(),password=document.getElementById('password')?.value,status=document.getElementById('authStatus');if(!email||!email.includes('@'))return toast('Enter a valid email address');if(password.length<6)return toast('Password must be at least 6 characters');if(status)status.textContent='Creating your account…';const {data,error}=await withTimeout(supabaseClient.auth.signUp({email,password,options:{data:{display_name:email.split('@')[0]}}}));if(error){const msg=authError(error);if(status)status.textContent=msg;return toast(msg)}if(data.session){if(status)status.textContent='Account created! Signing you in…';await bootstrap()}else{if(status)status.textContent='Account created. Check your email to confirm it, then sign in.';toast('Account created ✓ Check your email')}}
async function signOut(){await supabaseClient.auth.signOut();currentUser=null;state={tab:'home',habits:[],study:[],goals:[],quote:0,quotes:[],profile:null,leaderboard:[],loading:false,error:null};render()}
async function bootstrap(){state.error=null;state.loading=true;render();try{const {data:{session}}=await withTimeout(supabaseClient.auth.getSession());currentUser=session?.user||null;if(!currentUser){state.loading=false;render();return}await loadData();render()}catch(e){console.error(e);currentUser=null;state.loading=false;state.error=e?.message||'Unable to connect to Supabase.';render()}}
async function loadData(){const uid=currentUser.id;const results=await withTimeout(Promise.all([supabaseClient.from('profiles').select('display_name,xp,leaderboard_visible,role').eq('id',uid).maybeSingle(),supabaseClient.from('habits').select('*').eq('user_id',uid).eq('is_active',true).order('created_at'),supabaseClient.from('study_sessions').select('*').eq('user_id',uid).order('started_at',{ascending:false}),supabaseClient.from('goals').select('*, goal_milestones(*)').eq('user_id',uid).order('created_at'),supabaseClient.from('habit_completions').select('habit_id,completed_on').eq('user_id',uid),supabaseClient.from('quotes').select('text,author,category').eq('is_active',true)]),10000);const [p,h,s,g,m,q]=results;const firstError=[p,h,s,g,m,q].find(x=>x.error);if(firstError)throw new Error(firstError.error.message);const completions=m.data||[];state.profile=p.data||{display_name:currentUser.email?.split('@')[0]||'Quantum User',xp:0,leaderboard_visible:true,role:'user'};state.habits=(h.data||[]).map(x=>({...x,days:completions.filter(c=>c.habit_id===x.id).map(c=>c.completed_on)}));state.study=s.data||[];state.goals=(g.data||[]).map(x=>({...x,name:x.title,milestones:(x.goal_milestones||[]).sort((a,b)=>a.sort_order-b.sort_order)}));state.quotes=q.data||[];state.quote=state.quotes.length?Math.floor(Math.random()*state.quotes.length):0;state.loading=false}
function done(h){return h.days.includes(today())}
function streak(h){let d=new Date(),n=0;for(;;){const s=d.toISOString().slice(0,10);if(!h.days.includes(s))break;n++;d.setDate(d.getDate()-1)}return n}
function bestStreak(h){const days=[...new Set(h.days)].sort();let best=0,run=0,prev=null;for(const s of days){const d=new Date(s+'T00:00:00');if(prev&&((d-prev)/86400000===1))run++;else run=1;best=Math.max(best,run);prev=d}return best}
function totalStudy(){return state.study.reduce((a,s)=>a+(Number(s.duration_minutes)||0),0)}
function score(){return Math.round(state.habits.reduce((a,h)=>a+(done(h)?1:0),0)/Math.max(1,state.habits.length)*100)}
function xp(){return Number(state.profile?.xp||0)}
function level(){return Math.max(1,Math.floor(xp()/250)+1)}
function levelProgress(){const l=level(),start=(l-1)*250;return Math.min(100,Math.round((xp()-start)/250*100))}
function quoteText(){const q=state.quotes[state.quote];return q?`“${esc(q.text)}”${q.author?` — ${esc(q.author)}`:''}`:`“${quotesFallback[state.quote%quotesFallback.length]}”`}
function themeButton(){return `<button class="btn secondary" onclick="toggleTheme()">${document.documentElement.dataset.theme==='light'?'☀️':'🌙'}</button>`}
function shell(content,title){return `<div class="wrap"><div class="top"><div><div class="brand">QuantumFlow</div><div class="muted">${esc(title||new Date().toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric'}))}</div></div><div class="actions">${themeButton()}<button class="btn secondary" onclick="signOut()">Sign out</button></div></div>${content}</div>`}
function home(){const l=level(),pct=levelProgress(),next=l*250;return shell(`<div class="card hero"><div class="row between"><div><div class="muted">TODAY'S QUOTE</div><p class="quote">${quoteText()}</p></div>${themeButton()}</div><button class="btn secondary" onclick="newQuote()">✦ New quote</button></div><div class="card qf-xp"><div class="row between"><div><div class="muted">⚡ YOUR LEVEL</div><strong style="font-size:28px">Level ${l}</strong><div class="muted">${xp().toLocaleString()} XP</div></div><span class="badge">${Math.max(0,next-xp())} XP to next level</span></div><div class="bar" style="margin-top:10px"><i style="width:${pct}%"></i></div></div><div class="grid"><div class="card metric"><div class="muted">Today's score</div><strong>${score()}</strong><span class="muted">out of 100</span></div><div class="card metric"><div class="muted">Study time</div><strong>${(totalStudy()/60).toFixed(1)}h</strong><span class="muted">recorded</span></div><div class="card metric"><div class="muted">Best habit streak</div><strong>${Math.max(0,...state.habits.map(bestStreak),0)}</strong><span class="muted">days</span></div></div><div class="card"><div class="row between"><h3>Today's Habits</h3><button class="btn secondary" onclick="addHabit()">+ Add</button></div><div class="list">${state.habits.length?state.habits.map(h=>habitRow(h)).join(''):'<p class="muted">Create your first habit.</p>'}</div></div><div class="card"><div class="row between"><h3>Quick Focus</h3><button class="btn" onclick="focusTimer()">Start ${Math.round(timerTotal/60)}m</button></div><p class="muted">Customizable focus session. Completion adds study time and XP.</p></div><div class="card"><div class="row between"><h3>🏆 Leaderboard</h3><button class="btn secondary" onclick="openTab('leaderboard')">View rank</button></div><p class="muted">${state.profile?.leaderboard_visible===false?'You are currently hidden from the public leaderboard.':'You are eligible to appear on the leaderboard.'}</p></div></div>`)}
function habitRow(h){return `<div class="item"><button class="check ${done(h)?'done':''}" onclick="toggleHabit('${h.id}')">${done(h)?'✓':''}</button><div class="grow"><b>${esc(h.name)}</b><div class="muted">🔥 ${streak(h)} day streak · ${h.days.length} completions</div></div><span class="pill">${done(h)?'Done':'Today'}</span></div>`}
function habits(){return shell(`<div class="top"><div><h2>My Habits</h2><div class="muted">Build consistency one day at a time.</div></div><button class="btn" onclick="addHabit()">+ Habit</button></div>${state.habits.length?state.habits.map(h=>`<div class="card">${habitRow(h)}<div style="margin-top:12px" class="bar"><i style="width:${Math.min(100,h.days.length*3)}%"></i></div><div class="muted" style="margin-top:8px">Current ${streak(h)} · Best ${bestStreak(h)}</div></div>`).join(''):'<div class="card"><p class="muted">No habits yet. Add your first one above.</p></div>'}</div>`)}
function study(){return shell(`<div class="top"><div><h2>Study Planner</h2><div class="muted">Plan sessions and customize focus timing.</div></div><button class="btn" onclick="addStudy()">+ Session</button></div><div class="grid"><div class="card metric"><div class="muted">Total time</div><strong>${Math.round(totalStudy())}m</strong></div><div class="card metric"><div class="muted">Sessions</div><strong>${state.study.length}</strong></div></div><div class="card"><h3>⏱️ Custom Focus</h3><div class="muted">Choose 15, 25, 45, 60 minutes or enter your own 1–180 minute duration.</div><div class="actions" style="flex-wrap:wrap;margin-top:12px"><button class="btn secondary" onclick="setTimerMinutes(15)">15m</button><button class="btn secondary" onclick="setTimerMinutes(25)">25m</button><button class="btn secondary" onclick="setTimerMinutes(45)">45m</button><button class="btn secondary" onclick="setTimerMinutes(60)">60m</button><input id="customTimer" class="input" type="number" min="1" max="180" value="${Math.round(timerTotal/60)}" style="max-width:110px" placeholder="Custom"><button class="btn" onclick="setTimerMinutes(document.getElementById('customTimer').value)">Set</button></div><div class="timer" id="timer">${fmtTimer()}</div><div class="actions"><button class="btn" onclick="startTimer()">${timer?'Pause':'Start'}</button><button class="btn secondary" onclick="resetTimer()">Reset</button></div><p class="muted small">${timer?'Focus session running…':`${Math.round(timerTotal/60)} minute session ready`}</p></div><div class="card"><h3>Study history</h3><div class="list">${state.study.length?state.study.slice(0,20).map(s=>`<div class="item"><div class="grow"><b>${esc(s.title||'Study Session')}</b><div class="muted">${s.started_at?new Date(s.started_at).toLocaleString():'Today'} · ${s.duration_minutes} min</div></div><span class="pill green">${s.completed?'Completed':'Planned'}</span></div>`).join(''):'<p class="muted">No study sessions yet.</p>'}</div></div></div>`)}
function progress(){const completed=state.habits.reduce((a,h)=>a+h.days.length,0),best=Math.max(0,...state.habits.map(bestStreak),0);const totalGoalProgress=state.goals.length?Math.round(state.goals.reduce((a,g)=>a+Number(g.progress||0),0)/state.goals.length):0;return shell(`<h2>Progress</h2><div class="muted">Your cloud-saved consistency and productivity.</div><div class="grid"><div class="card metric"><strong>${completed}</strong><span class="muted">Habit completions</span></div><div class="card metric"><strong>${score()}%</strong><span class="muted">Today's consistency</span></div><div class="card metric"><strong>${best}</strong><span class="muted">Best streak</span></div><div class="card metric"><strong>${totalStudy()}m</strong><span class="muted">Study time</span></div><div class="card metric"><strong>${totalGoalProgress}%</strong><span class="muted">Average goal progress</span></div><div class="card metric"><strong>${xp()}</strong><span class="muted">Total XP</span></div></div><div class="card"><h3>Habit activity</h3><div class="heat">${Array.from({length:84},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(83-i));const key=d.toISOString().slice(0,10);const c=state.habits.reduce((n,h)=>n+(h.days.includes(key)?1:0),0);return `<i class="${c>=2?'on':c===1?'mid':''}" title="${key}: ${c} completion${c===1?'':'s'}"></i>`}).join('')}</div><div class="muted small" style="margin-top:8px">Last 12 weeks • darker cells mean more habits completed.</div></div></div>`)}
function goals(){return shell(`<div class="top"><div><h2>Goals</h2><div class="muted">Long-term progress powered by daily action.</div></div><button class="btn" onclick="addGoal()">+ Goal</button></div>${state.goals.length?state.goals.map(g=>`<div class="card"><div class="row between"><h3>${esc(g.name)}</h3><b>${Number(g.progress||0)}%</b></div><div class="bar"><i style="width:${Math.min(100,Number(g.progress||0))}%"></i></div><div class="muted" style="margin-top:10px">${g.milestones.length} milestones ${g.is_completed?'• Completed ✓':''}</div><div class="actions" style="margin-top:12px"><button class="btn secondary" onclick="advanceGoal('${g.id}',${Number(g.progress||0)})">${Number(g.progress||0)>=100?'Completed':'Update +10%'}</button></div></div>`).join(''):'<div class="card"><p class="muted">No goals yet. Add your first goal above.</p></div>'}</div>`)}
async function leaderboard(){if(!state.leaderboard.length){const {data,error}=await withTimeout(supabaseClient.rpc('leaderboard_top',{p_limit:50}));if(!error)state.leaderboard=data||[];else return shell(`<div class="card"><h2>🏆 Leaderboard</h2><p class="muted">${esc(error.message)}</p></div>`)}const mine=state.leaderboard.find(x=>x.user_id===currentUser.id);return shell(`<div class="top"><div><h2>🏆 Leaderboard</h2><div class="muted">Consistency matters more than perfection.</div></div><span class="badge">${mine?`Your rank #${mine.rank} • ⚡ ${mine.xp} XP`:'Not publicly ranked'}</span></div><div class="card"><div class="list">${state.leaderboard.length?state.leaderboard.map(r=>`<div class="item" style="${r.user_id===currentUser.id?'background:color-mix(in srgb,var(--primary) 12%,transparent);border-radius:12px':''}"><strong style="min-width:42px">${r.rank<=3?['🥇','🥈','🥉'][r.rank-1]:'#'+r.rank}</strong><div class="grow"><b>${esc(r.display_name)}</b><div class="muted">Productive progress</div></div><b>⚡ ${Number(r.xp||0).toLocaleString()}</b></div>`).join(''):'<p class="muted">No public leaderboard users yet.</p>'}</div></div><p class="muted small">Only users who choose to appear are shown. Emails are never displayed.</p>`)}
function profile(){return shell(`<div class="card hero"><div class="brand">PROFILE</div><h2>${esc(state.profile?.display_name||'Quantum User')}</h2><p class="muted">${esc(currentUser.email||'')}</p><div class="grid"><div class="card metric"><div class="muted">⚡ XP</div><strong>${xp()}</strong></div><div class="card metric"><div class="muted">Level</div><strong>${level()}</strong></div><div class="card metric"><div class="muted">Habits</div><strong>${state.habits.length}</strong></div><div class="card metric"><div class="muted">Goals</div><strong>${state.goals.length}</strong></div></div><div class="row between" style="margin-top:14px"><div><b>Leaderboard visibility</b><div class="muted small">Allow your display name and XP to appear publicly.</div></div><button class="btn ${state.profile?.leaderboard_visible===false?'secondary':''}" onclick="toggleLeaderboardVisibility()">${state.profile?.leaderboard_visible===false?'Hidden':'Visible'}</button></div></div>`)}
function admin(){return shell(`<div class="card"><h2>🛡️ Admin</h2><p class="muted">Admin analytics remains protected in the dedicated dashboard.</p><a class="btn" href="admin.html">Open Admin Dashboard</a></div>`)}
function render(){const app=document.getElementById('app');if(!app)return;if(state.loading){app.innerHTML='<div class="wrap"><div class="card"><h2>Loading QuantumFlow…</h2><p class="muted">Syncing your data.</p></div></div>';document.getElementById('nav').innerHTML='';return}if(state.error){app.innerHTML=errorView();document.getElementById('nav').innerHTML='';return}if(!currentUser){app.innerHTML=auth();document.getElementById('nav').innerHTML='';return}const views={home,habits,study,progress,goals,leaderboard,profile,admin};const view=views[state.tab]||home;const result=view();if(result instanceof Promise){app.innerHTML='<div class="wrap"><div class="card"><h2>Loading…</h2></div></div>';result.then(html=>{if(state.tab===Object.keys(views).find(k=>views[k]===view))app.innerHTML=html;});}else app.innerHTML=result;const items=[['home','⌂','Home'],['habits','✓','Habits'],['study','▣','Study'],['progress','◒','Progress'],['goals','◆','Goals'],['leaderboard','🏆','Rank'],['profile','●','Profile']];if(state.profile?.role==='admin')items.push(['admin','🛡','Admin']);document.getElementById('nav').className='nav';document.getElementById('nav').innerHTML=items.map(x=>`<button class="${state.tab===x[0]?'active':''}" onclick="openTab('${x[0]}')"><b>${x[1]}</b>${x[2]}</button>`).join('')}
function openTab(tab){state.tab=tab;if(tab==='leaderboard')state.leaderboard=[];render()}
async function newQuote(){if(state.quotes.length){state.quote=(state.quote+1)%state.quotes.length}else state.quote=(state.quote+1)%quotesFallback.length;render();toast('New quote ✦')}
async function addHabit(){const n=prompt('Habit name');if(!n?.trim())return;const {data,error}=await withTimeout(supabaseClient.from('habits').insert({user_id:currentUser.id,name:n.trim()}).select().single());if(error)return toast(error.message);state.habits.push({...data,days:[]});render();toast('Habit created')}
async function toggleHabit(id){const h=state.habits.find(x=>x.id===id);if(!h)return;const d=today();if(done(h)){const {error}=await withTimeout(supabaseClient.from('habit_completions').delete().eq('habit_id',id).eq('completed_on',d).eq('user_id',currentUser.id));if(error)return toast(error.message);h.days=h.days.filter(x=>x!==d);toast('Habit unchecked')}else{const {data,error}=await withTimeout(supabaseClient.from('habit_completions').insert({habit_id:id,user_id:currentUser.id,completed_on:d}).select().single());if(error)return toast(error.message);h.days.push(d);await awardXP(`habit:${id}:${d}`,10);toast('Habit completed ✓ +10 XP')}await refreshProfile();render()}
async function addStudy(){const n=prompt('Study session name');if(!n?.trim())return;const d=Number(prompt('Duration in minutes','30'));if(!Number.isFinite(d)||d<=0)return;const {data,error}=await withTimeout(supabaseClient.from('study_sessions').insert({user_id:currentUser.id,title:n.trim(),started_at:new Date(Date.now()-d*60000).toISOString(),ended_at:new Date().toISOString(),duration_minutes:d,completed:true}).select().single());if(error)return toast(error.message);state.study.unshift(data);await awardXP(`study:${data.id}`,Math.max(10,Math.min(60,Math.round(d/2))));await refreshProfile();render();toast('Study session saved ✓')}
async function addGoal(){const n=prompt('Goal name');if(!n?.trim())return;const {data,error}=await withTimeout(supabaseClient.from('goals').insert({user_id:currentUser.id,title:n.trim(),progress:0}).select().single());if(error)return toast(error.message);const {data:milestone}=await withTimeout(supabaseClient.from('goal_milestones').insert({goal_id:data.id,user_id:currentUser.id,title:'First milestone',sort_order:0}).select().single());state.goals.push({...data,name:data.title,milestones:milestone?[milestone]:[]});render();toast('Goal created')}
async function advanceGoal(id,current){const next=Math.min(100,current+10);const {error}=await withTimeout(supabaseClient.from('goals').update({progress:next,is_completed:next===100,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',currentUser.id));if(error)return toast(error.message);const g=state.goals.find(x=>x.id===id);if(g){g.progress=next;g.is_completed=next===100}if(next===100&&current<100){await awardXP(`goal:${id}:complete`,50);toast('Goal completed 🎯 +50 XP')}else toast('Goal updated');await refreshProfile();render()}
function fmtTimer(){return `${String(Math.floor(secs/60)).padStart(2,'0')}:${String(secs%60).padStart(2,'0')}`}
function setTimerMinutes(m){m=Math.max(1,Math.min(180,Math.round(Number(m)||25)));if(timer){clearInterval(timer);timer=null}secs=m*60;timerTotal=secs;localStorage.setItem('qf-focus-secs',String(secs));updateTimer();render();toast(`${m} minute focus session set`)}
function startTimer(){if(timer){clearInterval(timer);timer=null;render();return}timerStartedAt=Date.now();timer=setInterval(()=>{secs--;updateTimer();if(secs<=0){clearInterval(timer);timer=null;saveFocusSession()}},1000);render();toast('Focus started')}
async function saveFocusSession(){const duration=Math.max(1,Math.round(timerTotal/60));const start=new Date(Date.now()-duration*60000).toISOString();const {data,error}=await withTimeout(supabaseClient.from('study_sessions').insert({user_id:currentUser.id,title:'Focus Session',started_at:start,ended_at:new Date().toISOString(),duration_minutes:duration,completed:true}).select().single());if(!error&&data){state.study.unshift(data);await awardXP(`focus:${data.id}`,Math.max(10,Math.min(60,Math.round(duration/2))))}secs=timerTotal;localStorage.setItem('qf-focus-secs',String(secs));await refreshProfile();render();toast(error?'Could not save focus session':`Focus session complete 🎉 +${Math.max(10,Math.min(60,Math.round(duration/2)))} XP`)}
function updateTimer(){const e=document.getElementById('timer');if(e)e.textContent=fmtTimer()}
function focusTimer(){state.tab='study';render()}
function resetTimer(){if(timer){clearInterval(timer);timer=null}secs=timerTotal;updateTimer();render();toast('Timer reset')}
async function awardXP(sourceId,points){try{const {error}=await withTimeout(supabaseClient.rpc('grant_xp',{p_event_key:'activity',p_source_id:sourceId,p_points:points}),10000);if(error)console.warn('XP award failed',error.message)}catch(e){console.warn('XP award failed',e.message)}}
async function refreshProfile(){if(!currentUser)return;const {data}=await supabaseClient.from('profiles').select('display_name,xp,leaderboard_visible,role').eq('id',currentUser.id).maybeSingle();if(data)state.profile=data}
function toggleTheme(){const n=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=n;localStorage.setItem('qf-theme',n);render()}
async function toggleLeaderboardVisibility(){const next=state.profile?.leaderboard_visible===false;const {error}=await withTimeout(supabaseClient.from('profiles').update({leaderboard_visible:next}).eq('id',currentUser.id));if(error)return toast(error.message);state.profile.leaderboard_visible=next;toast(next?'Leaderboard visibility enabled':'Leaderboard visibility disabled');render()}
const savedTheme=localStorage.getItem('qf-theme')||'dark';document.documentElement.dataset.theme=savedTheme==='light'?'light':'dark';
bootstrap();