// QuantumFlow authentication UI — canonical auth screen.
(() => {
  const WAIT_MS = 65_000;
  let lockedUntil = 0;
  function authMode(mode='signin') {
    const root=document.getElementById('authScreen'); if(!root)return;
    root.dataset.authMode=mode;
    const name=document.getElementById('displayName'), title=document.getElementById('authTitle'), submit=document.getElementById('authSubmit'), switcher=document.getElementById('authSwitcher');
    if(name) name.hidden=mode!=='signup';
    if(title) title.textContent=mode==='signup'?'Create your account':'Welcome back';
    if(submit){submit.textContent=mode==='signup'?'Create account':'Sign in';submit.onclick=mode==='signup'?window.signUp:window.signIn;}
    if(switcher)switcher.innerHTML=mode==='signup'?`Already have an account? <button type="button" class="link-btn" onclick="qfAuthMode('signin')">Sign in</button>`:`New to QuantumFlow? <button type="button" class="link-btn" onclick="qfAuthMode('signup')">Create account</button>`;
  }
  window.qfAuthMode=authMode;
  window.auth=function(){return `<div id="authScreen" class="wrap auth" data-auth-mode="signin"><div class="card hero qf-auth-card"><div data-qf-auth-robot="true" class="qf-auth-robot" aria-hidden="true">🤖</div><div class="brand">QuantumFlow</div><h1 id="authTitle">Welcome back</h1><p class="muted">Build better days. Track habits, study, goals and progress in one place.</p><input id="displayName" class="input" type="text" autocomplete="name" placeholder="Your Name" hidden><input id="email" class="input" type="email" autocomplete="email" placeholder="Email ID"><input id="password" class="input" type="password" autocomplete="current-password" placeholder="Password (6+ characters)"><div class="actions"><button id="authSubmit" class="btn" type="button" onclick="signIn()">Sign in</button></div><p id="authSwitcher" class="muted small">New to QuantumFlow? <button type="button" class="link-btn" onclick="qfAuthMode('signup')">Create account</button></p><p id="authStatus" class="muted small"></p><p class="muted small">If email confirmation is enabled, confirm your email before signing in.</p></div><style>.qf-auth-card{position:relative;overflow:hidden}.qf-auth-robot{font-size:clamp(44px,12vw,72px);line-height:1;margin:0 auto 12px;text-align:center;filter:drop-shadow(0 8px 18px rgba(120,180,255,.25));animation:qfRobotFloat 3.2s ease-in-out infinite}.link-btn{border:0;background:transparent;color:inherit;text-decoration:underline;cursor:pointer;font:inherit;padding:0}#displayName[hidden]{display:none!important}@keyframes qfRobotFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-7px)}}@media(prefers-reduced-motion:reduce){.qf-auth-robot{animation:none}}</style></div>`;};
  window.signUp=async function(){const now=Date.now();if(now<lockedUntil)return toast(`Please wait ${Math.ceil((lockedUntil-now)/1000)}s before trying again.`);const name=document.getElementById('displayName')?.value.trim(),email=document.getElementById('email')?.value.trim().toLowerCase(),password=document.getElementById('password')?.value||'',status=document.getElementById('authStatus');if(!name)return toast('Enter your name');if(!email||!email.includes('@'))return toast('Enter a valid email ID');if(password.length<6)return toast('Password must be at least 6 characters');lockedUntil=now+WAIT_MS;if(status)status.textContent='Creating your account…';try{const {data,error}=await supabaseClient.auth.signUp({email,password,options:{emailRedirectTo:window.location.origin+window.location.pathname,data:{display_name:name,full_name:name,name:name}}});if(error){lockedUntil=0;const m=String(error.message||'').toLowerCase(),friendly=error.status===429||m.includes('rate limit')||m.includes('rate_limit')?'Email sending limit reached. Please wait and try again.':error.message;if(status)status.textContent=friendly;return toast(friendly)}if(data?.session){lockedUntil=0;if(status)status.textContent='Account created! Signing you in…';return bootstrap()}if(status)status.textContent='Account created. Check your email ID to confirm your account.';toast('Account created ✓ Check your email')}catch(err){lockedUntil=0;const msg=err?.message||'Could not create the account.';if(status)status.textContent=msg;toast(msg)}};
  const cleanRobots=()=>{const root=document.getElementById('authScreen');if(!root)return;root.querySelectorAll('[data-qf-auth-robot]').forEach((el,i)=>{if(i>0)el.remove()});};new MutationObserver(cleanRobots).observe(document.body,{childList:true,subtree:true});
})();
