// QuantumFlow auth UI — reference-inspired robot login/create-account experience.
(() => {
  const WAIT_MS = 65000;
  let lockedUntil = 0;
  let mode = 'signin';
  let lastRoot = null;

  const icon = (name) => ({mail:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></svg>',lock:'<svg viewBox="0 0 24 24"><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>',eye:'<svg viewBox="0 0 24 24"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/></svg>'}[name]||'');
  function theme(){const saved=localStorage.getItem('qf-theme');const current=saved==='dark'?'dark':'light';document.documentElement.setAttribute('data-theme',current);return current}
  function toggleTheme(){const next=document.documentElement.getAttribute('data-theme')==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',next);localStorage.setItem('qf-theme',next);const b=document.getElementById('qfThemeToggle');if(b){b.textContent=next==='dark'?'☀️ Light':'🌙 Dark';b.setAttribute('aria-label',`Switch to ${next==='dark'?'light':'dark'} theme`)}}
  theme();
  function installAuthLayoutFix(){if(document.getElementById('qf-auth-layout-fix'))return;const s=document.createElement('style');s.id='qf-auth-layout-fix';s.textContent='#app .auth .qf-auth-card{padding-top:82px;position:relative}#app .auth .qf-auth-robot{top:-145px}#app .auth .qf-auth-panel{position:relative;z-index:3}#app .auth .qf-auth-bubble{z-index:7}';document.head.appendChild(s)}
  function robotMarkup(){return `<div class="qf-auth-robot" aria-hidden="true"><div class="qf-auth-bubble">Quantum Flow</div><div class="qf-robot-wrap"><div class="qf-robot-head"><div class="qf-robot-face"><i></i><i></i><b></b><em></em><em></em></div></div></div></div>`}
  function field(id,type,placeholder,autocomplete,ico){return `<label class="qf-auth-field" for="${id}"><span class="qf-field-icon">${icon(ico)}</span><input id="${id}" class="input" type="${type}" autocomplete="${autocomplete}" placeholder="${placeholder}">${id==='password'?`<button class="qf-password-toggle" type="button" aria-label="Show password" onclick="window.qfTogglePassword()">${icon('eye')}</button>`:''}</label>`}
  function build(root){const card=root.querySelector('.card.hero');if(!card)return;installAuthLayoutFix();card.classList.add('qf-auth-card');const isDark=document.documentElement.getAttribute('data-theme')==='dark';card.innerHTML=`<button id="qfThemeToggle" class="qf-auth-theme-toggle" type="button" aria-label="Switch to ${isDark?'light':'dark'} theme">${isDark?'☀️ Light':'🌙 Dark'}</button>${robotMarkup()}<div class="qf-auth-panel">${mode==='signin'?'<div class="qf-welcome">Welcome to Quantum Flow</div>':''}<div class="qf-auth-title">Beep boop. ${mode==='signup'?'New human detected!':'Who goes there?'}</div><div class="qf-auth-subtitle">${mode==='signup'?'Create your QuantumFlow account and start building better days.':'Log in and keep your momentum going.'}</div><form id="qfAuthForm" class="qf-auth-form" novalidate>${field('email','email','Your email','email','mail')}${field('password','password','Super secret password','new-password','lock')}<button id="qfAuthSubmit" class="qf-auth-submit" type="submit"><span>⚡</span>${mode==='signup'?'CREATE ACCOUNT':'LOG ME IN'}</button></form><p id="authStatus" class="qf-auth-status" aria-live="polite"></p><div class="qf-auth-switch">${mode==='signup'?'Already have an account?':"Don't have an account?"} <button id="qfAuthSwitch" type="button">${mode==='signup'?'Sign in':'Create account'}</button></div><p class="qf-auth-note">Your account is secured with Supabase authentication.</p></div>`;card.querySelector('#qfThemeToggle').onclick=toggleTheme;card.querySelector('#qfAuthForm').addEventListener('submit',e=>{e.preventDefault();mode==='signup'?window.signUp():window.signIn()});card.querySelector('#qfAuthSwitch').onclick=()=>{mode=mode==='signup'?'signin':'signup';lastRoot=null;renderAuth()}}
  function renderAuth(){const root=document.querySelector('#app .auth');if(!root)return;if(root!==lastRoot||!root.querySelector('.qf-auth-card')){lastRoot=root;build(root)}}
  window.qfTogglePassword=()=>{const i=document.getElementById('password');if(i)i.type=i.type==='password'?'text':'password'};
  window.signUp=async()=>{const now=Date.now();if(now<lockedUntil)return toast(`Please wait ${Math.ceil((lockedUntil-now)/1000)}s before trying again.`);const email=String(document.getElementById('email')?.value||'').trim().toLowerCase(),password=document.getElementById('password')?.value||'',status=document.getElementById('authStatus');if(!email||!email.includes('@'))return toast('Enter a valid email ID');if(password.length<6)return toast('Password must be at least 6 characters');lockedUntil=now+WAIT_MS;if(status)status.textContent='Creating your account…';try{const {data,error}=await Promise.race([supabaseClient.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}}),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Request timed out. Please check your internet connection.')),10000))]);if(error){lockedUntil=0;return toast(error.message)}if(data?.session){lockedUntil=0;return bootstrap()}if(status)status.textContent='Account created. Check your email ID to confirm your account.';toast('Account created ✓ Check your email')}catch(e){lockedUntil=0;toast(e?.message||'Could not create the account.')}};
  new MutationObserver(renderAuth).observe(document.body,{childList:true,subtree:true});setTimeout(renderAuth,0);
})();