// Quantum Flow current auth UI. This file intentionally replaces all legacy auth UI handlers.
(() => {
  const WAIT_MS = 65000;
  let lockedUntil = 0;
  let mode = 'signin';
  let lastRoot = null;
  const icon = n => ({mail:'<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/>',lock:'<svg viewBox="0 0 24 24"><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',eye:'<svg viewBox="0 0 24 24"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/></svg>'}[n]||'');
  const setTheme=()=>{const s=localStorage.getItem('qf-theme');document.documentElement.setAttribute('data-theme',s==='dark'?'dark':'light')};
  const toggleTheme=()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem('qf-theme',n);const b=document.getElementById('qfThemeToggle');if(b)b.textContent=n==='dark'?'☀️ Light':'🌙 Dark'};
  setTheme();
  function layout(){if(document.getElementById('qf-auth-layout-fix'))return;const s=document.createElement('style');s.id='qf-auth-layout-fix';s.textContent='#app .auth .qf-auth-card{padding-top:82px;position:relative}#app .auth .qf-auth-panel{position:relative;z-index:3}#app .auth .qf-auth-bubble{z-index:7}';document.head.appendChild(s)}
  const robot=()=>'<div class="qf-auth-robot" aria-hidden="true"><div class="qf-auth-bubble">Quantum Flow</div><div class="qf-robot-wrap"><div class="qf-robot-head"><div class="qf-robot-face"><i></i><i></i><b></b><em></em><em></em></div></div></div></div>';
  const field=(id,type,placeholder,autocomplete,ico)=>`<label class="qf-auth-field" for="${id}"><span class="qf-field-icon">${icon(ico)}</span><input id="${id}" class="input" type="${type}" autocomplete="${autocomplete}" placeholder="${placeholder}" required>${id==='password'?`<button class="qf-password-toggle" type="button" aria-label="Show password" onclick="qfTogglePassword()">${icon('eye')}</button>`:''}</label>`;
  function build(root){const card=root.querySelector('.card.hero');if(!card)return;layout();const dark=document.documentElement.dataset.theme==='dark';card.classList.add('qf-auth-card');card.innerHTML=`<button id="qfThemeToggle" class="qf-auth-theme-toggle" type="button">${dark?'☀️ Light':'🌙 Dark'}</button>${robot()}<div class="qf-auth-panel">${mode==='signin'?'<div class="qf-welcome">Welcome to Quantum Flow</div>':''}<div class="qf-auth-title">Beep boop. ${mode==='signup'?'New human detected!':'Who goes there?'}</div><div class="qf-auth-subtitle">${mode==='signup'?'Create your Quantum Flow account and start building better days.':'Log in and keep your momentum going.'}</div><form id="qfAuthForm" class="qf-auth-form" novalidate>${field('email','email','Your email','email','mail')}${field('password','password','Super secret password','current-password','lock')}<button class="qf-auth-submit" type="submit"><span>⚡</span>${mode==='signup'?'CREATE ACCOUNT':'LOG ME IN'}</button></form><p id="authStatus" class="qf-auth-status" aria-live="polite"></p><div class="qf-auth-switch">${mode==='signup'?'Already have an account?':"Don't have an account?"} <button id="qfAuthSwitch" type="button">${mode==='signup'?'Sign in':'Create account'}</button></div><p class="qf-auth-note">Your account is secured with Supabase authentication.</p></div>`;card.querySelector('#qfThemeToggle').onclick=toggleTheme;card.querySelector('#qfAuthForm').addEventListener('submit',e=>{e.preventDefault();mode==='signup'?window.qfCreateAccount():window.qfLogin()});card.querySelector('#qfAuthSwitch').onclick=()=>{mode=mode==='signup'?'signin':'signup';lastRoot=null;render()}}
  function render(){const root=document.querySelector('#app .auth');if(!root)return;if(root!==lastRoot||!root.querySelector('.qf-auth-card')){lastRoot=root;build(root)}}
  const normalizeEmail=e=>String(e||'').trim().toLowerCase();
  const validateEmail=e=>{const value=normalizeEmail(e);if(!value||value.length>254)return 'Enter a valid email address.';if(/[\s,;<>()[\]\\"']/u.test(value))return 'Enter a valid email address.';const parts=value.split('@');if(parts.length!==2)return 'Enter a valid email address.';const [local,domain]=parts;if(!local||local.length>64||local.startsWith('.')||local.endsWith('.')||local.includes('..'))return 'Enter a valid email address.';if(!/^[a-z0-9!#$%&'*+/=?^_`{|}~.-]+$/i.test(local))return 'Enter a valid email address.';if(!domain||domain.length>253||domain.startsWith('.')||domain.endsWith('.')||domain.includes('..'))return 'Enter a valid email address.';const labels=domain.split('.');if(labels.length<2||labels.some(x=>!x||x.length>63||x.startsWith('-')||x.endsWith('-')||!/^[a-z0-9-]+$/i.test(x)))return 'Enter a valid email address.';const tld=labels.at(-1);if(tld.length<2||/^\d+$/.test(tld))return 'Enter a valid email address.';const blocked=['example.com','example.org','example.net','invalid','localhost','test','test.com','example'];if(blocked.includes(domain)||blocked.some(x=>domain.endsWith('.'+x)))return 'Please use a real email address, not a placeholder/test address.';return '';};
  window.qfTogglePassword=()=>{const i=document.getElementById('password');if(i)i.type=i.type==='password'?'text':'password'};
  window.qfLogin=async()=>{const e=normalizeEmail(document.getElementById('email')?.value),p=document.getElementById('password')?.value||'',validation=validateEmail(e),s=document.getElementById('authStatus');if(validation)return toast(validation);if(!p)return toast('Enter your password');if(p.length<6)return toast('Password must be at least 6 characters');if(s)s.textContent='Signing you in…';try{const r=await supabaseClient.auth.signInWithPassword({email:e,password:p});if(r.error){if(s)s.textContent='';const msg=r.error.message||'';if(/email.*not.*confirm|not.*verified|confirm.*email/i.test(msg))return toast('Please verify your email before logging in.');return toast(msg)}await bootstrap()}catch(x){if(s)s.textContent='';toast(x?.message||'Could not sign in.')}};
  window.qfCreateAccount=async()=>{const now=Date.now();if(now<lockedUntil)return toast(`Please wait ${Math.ceil((lockedUntil-now)/1000)}s before trying again.`);const e=normalizeEmail(document.getElementById('email')?.value),p=document.getElementById('password')?.value||'',s=document.getElementById('authStatus'),validation=validateEmail(e);if(validation)return toast(validation);if(p.length<6)return toast('Password must be at least 6 characters');lockedUntil=now+WAIT_MS;if(s)s.textContent='Creating your account…';try{const r=await Promise.race([supabaseClient.auth.signUp({email:e,password:p}),new Promise((_,reject)=>setTimeout(()=>reject(new Error('Request timed out. Please check your internet connection.')),10000))]);if(r.error){lockedUntil=0;if(s)s.textContent=r.error.message;return toast(r.error.message)}const session=r.data?.session;if(session){lockedUntil=0;if(s)s.textContent='Account created successfully.';return bootstrap()}const current=await supabaseClient.auth.getSession();if(current.data?.session){lockedUntil=0;if(s)s.textContent='Account created successfully.';return bootstrap()}lockedUntil=0;if(s)s.textContent='Account created. Please check your email to verify your account before logging in.';return toast('Account created. Check your email to verify your account.')}catch(x){lockedUntil=0;if(s)s.textContent=x?.message||'Could not create the account.';toast(x?.message||'Could not create the account.')}};
  new MutationObserver(render).observe(document.body,{childList:true,subtree:true});setTimeout(render,0);
})();
