/* Quantum Flow Admin — secure user detail viewer. */
(()=>{'use strict';
const client=()=>window.qfSupabaseClient||window.supabaseClient||(window.supabase?.createClient?null:null);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const fmt=d=>d?new Date(d).toLocaleDateString([], {year:'numeric',month:'short',day:'numeric'}):'—';
const initials=s=>(String(s||'?').trim()[0]||'?').toUpperCase();
async function view(id){
 if(!id)return;
 document.getElementById('qfAdminUserModal')?.remove();
 const modal=document.createElement('div');modal.id='qfAdminUserModal';modal.className='admin-user-modal';
 modal.innerHTML='<div class="admin-user-dialog"><div class="admin-user-head"><div class="admin-user-title"><div class="admin-user-avatar">…</div><div><div class="muted">USER INTELLIGENCE</div><h2 style="margin:3px 0">Loading profile…</h2></div></div><button class="admin-user-close" aria-label="Close">×</button></div><div class="admin-user-body"><div class="admin-loading">Loading habits, goals, targets and milestones…</div></div></div>';
 document.body.appendChild(modal);modal.querySelector('.admin-user-close').onclick=()=>modal.remove();modal.addEventListener('click',e=>{if(e.target===modal)modal.remove()});
 try{
  const sb=client();
  if(!sb) throw new Error('Supabase client is not available. Please refresh the admin page.');
  const {data,error}=await sb.rpc('admin_user_detail',{p_user_id:id});
  if(error)throw error;
  const payload=Array.isArray(data)?(data[0]||{}):(data||{});
  const p=payload.profile||{},goals=Array.isArray(payload.goals)?payload.goals:[],habits=Array.isArray(payload.habits)?payload.habits:[],name=p.display_name||p.email?.split('@')[0]||'Quantum User';
  modal.querySelector('.admin-user-avatar').textContent=initials(name);modal.querySelector('.admin-user-title h2').textContent=name;modal.querySelector('.admin-user-title .muted').textContent=p.email||'Private account';
  const active=habits.filter(h=>h.is_active).length,completedGoals=goals.filter(g=>g.is_completed||Number(g.progress)>=100).length,milestones=goals.reduce((n,g)=>n+(Array.isArray(g.milestones)?g.milestones.length:0),0),completedMilestones=goals.reduce((n,g)=>n+(Array.isArray(g.milestones)?g.milestones.filter(m=>m.is_completed).length:0),0),habitTarget=habits.reduce((n,h)=>n+Number(h.target_per_week||0),0);
  const goalHtml=goals.length?goals.map(g=>{const pct=Math.max(0,Math.min(100,Number(g.progress)||0)),ms=Array.isArray(g.milestones)?g.milestones:[],doneMs=ms.filter(m=>m.is_completed).length;return `<article class="admin-goal"><div class="admin-goal-top"><div><h4>🎯 ${esc(g.title||'Untitled goal')}</h4><div class="muted">${esc(g.description||'No description')} ${g.deadline?`• Due ${fmt(g.deadline)}`:''}</div></div><b>${pct}%</b></div><div class="admin-target-row"><span>Target</span><strong>100%</strong><span>Current</span><strong>${pct}%</strong></div><div class="admin-progress"><i style="width:${pct}%"></i></div>${ms.length?`<div class="admin-milestones-head"><span>Milestones</span><b>${doneMs}/${ms.length}</b></div><div class="admin-milestones">${ms.map(m=>`<div class="admin-milestone"><span class="admin-milestone-dot ${m.is_completed?'done':''}">${m.is_completed?'✓':''}</span><span>${esc(m.title||'Milestone')}</span><span class="admin-milestone-status">${m.is_completed?'Completed':'Pending'}</span></div>`).join('')}</div>`:'<div class="muted small">No milestones added.</div>'}</article>`}).join(''):'<div class="admin-empty">🎯 This user has not created any goals.</div>';
  const habitHtml=habits.length?habits.map(h=>{const dates=Array.isArray(h.recent_completions)?h.recent_completions:[],target=Number(h.target_per_week||0),count=Number(h.completion_count||0);return `<article class="admin-habit"><div class="admin-habit-top"><div><h4>${esc(h.icon||'🌱')} ${esc(h.name||'Untitled habit')}</h4><div class="muted">${esc(h.description||'No description')} • ${esc(h.frequency||'Custom')}</div></div><span class="badge">${h.is_active?'Active':'Paused'}</span></div><div class="admin-target-grid"><div><span>Weekly target</span><strong>${target}×</strong></div><div><span>Total completions</span><strong>${count}</strong></div></div><div class="muted" style="margin-top:8px">${h.reminder_time?`⏰ Reminder ${esc(String(h.reminder_time).slice(0,5))}`:'⏰ No reminder set'}</div>${dates.length?`<div class="admin-completion-list">${dates.slice(0,12).map(d=>`<span class="admin-date-pill">✓ ${fmt(d)}</span>`).join('')}</div>`:'<div class="muted small" style="margin-top:8px">No completions recorded.</div>'}</article>`}).join(''):'<div class="admin-empty">🌱 This user has not created any habits.</div>';
  modal.querySelector('.admin-user-body').innerHTML=`<div class="admin-user-stats"><div class="admin-user-stat"><span class="muted">⚡ XP</span><strong>${Number(p.xp||0).toLocaleString()}</strong></div><div class="admin-user-stat"><span class="muted">🎯 Goals</span><strong>${goals.length}</strong></div><div class="admin-user-stat"><span class="muted">🌱 Active habits</span><strong>${active}</strong></div><div class="admin-user-stat"><span class="muted">🧩 Milestones</span><strong>${completedMilestones}/${milestones}</strong></div></div><section class="admin-user-section"><div class="admin-user-section-head"><div><h3>🎯 Goals, targets & milestones</h3><div class="muted">${completedGoals}/${goals.length} goals completed • ${completedMilestones}/${milestones} milestones completed</div></div></div><div class="admin-user-list">${goalHtml}</div></section><section class="admin-user-section"><div class="admin-user-section-head"><div><h3>🌱 Habit tracker & targets</h3><div class="muted">Current habits, weekly targets and recent completion history • ${habitTarget} total weekly target check-ins</div></div></div><div class="admin-user-list">${habitHtml}</div></section><section class="admin-user-section"><div class="muted">Account created ${fmt(p.created_at)} • Last profile update ${fmt(p.updated_at)} • Leaderboard ${p.leaderboard_visible===false?'hidden':'visible'}</div></section>`;
 }catch(e){modal.querySelector('.admin-user-body').innerHTML=`<div class="notice error"><strong>Could not load this user's details.</strong><br><span class="muted">${esc(e.message||'Unknown error')}</span><div style="margin-top:10px"><button class="btn secondary" onclick="this.closest('.admin-user-modal').remove()">Close</button></div></div>`}
}
window.viewAdminUser=view})();