(()=>{
  const db=()=>window.supabaseClient;
  const esc=(s)=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  const user=()=>window.currentUser||window.__qfUser;
  const toastMsg=(m)=>window.toast?window.toast(m):alert(m);
  const editor=(title,body,save)=>{document.getElementById('qf-editor')?.remove();const x=document.createElement('div');x.id='qf-editor';x.className='qf-editor-backdrop';x.innerHTML=`<div class="qf-editor-card"><div class="row between"><h3>${esc(title)}</h3><button class="btn secondary" id="qf-close">✕</button></div><div class="qf-editor-body">${body}</div><div class="actions qf-editor-actions"><button class="btn secondary" id="qf-cancel">Cancel</button><button class="btn" id="qf-save">Save</button></div></div>`;document.body.appendChild(x);const close=()=>x.remove();x.querySelector('#qf-close').onclick=close;x.querySelector('#qf-cancel').onclick=close;x.querySelector('#qf-save').onclick=async()=>{const b=x.querySelector('#qf-save');b.disabled=true;b.textContent='Saving…';try{await save(x);close()}catch(e){console.error(e);b.disabled=false;b.textContent='Save';toastMsg(e.message||'Save failed')}}};
  const v=(x,id)=>x.querySelector('#'+id)?.value?.trim()||'';
  const requireUser=()=>{if(!user()?.id)throw new Error('Please sign in again before editing.');return user().id};
  const fail=(e,msg)=>{if(e)throw new Error(msg+': '+(e.message||'Database error'))};

  window.editHabit=(id)=>{const h=state.habits.find(a=>a.id===id);if(!h)return;editor('Edit habit',`<label>Name<input id="n" class="input" maxlength="80" value="${esc(h.name)}"></label><label>Description<input id="d" class="input" maxlength="240" value="${esc(h.description||'')}"></label><label>Frequency<select id="f" class="input"><option value="daily" ${h.frequency==='daily'?'selected':''}>Daily</option><option value="weekly" ${h.frequency==='weekly'?'selected':''}>Weekly</option><option value="custom" ${h.frequency==='custom'?'selected':''}>Custom</option></select></label><label>Target per week<input id="t" class="input" type="number" min="1" max="7" value="${Math.max(1,Math.min(7,Number(h.target_per_week)||7))}"></label>`,async x=>{const uid=requireUser(),name=v(x,'n');if(!name)throw new Error('Enter a habit name.');const patch={name,description:v(x,'d')||null,frequency:v(x,'f')||'daily',target_per_week:Math.max(1,Math.min(7,Number(x.querySelector('#t').value)||7))};const r=await db().from('habits').update(patch).eq('id',id).eq('user_id',uid).select('*').single();fail(r.error,'Unable to update habit');Object.assign(h,patch);render();toastMsg('Habit updated ✓')})};
  window.deleteHabit=async(id)=>{if(!confirm('Delete this habit? Its completion history will also be removed.'))return;try{const uid=requireUser();let r=await db().from('habit_completions').delete().eq('habit_id',id).eq('user_id',uid);fail(r.error,'Unable to delete completions');r=await db().from('habits').delete().eq('id',id).eq('user_id',uid);fail(r.error,'Unable to delete habit');state.habits=state.habits.filter(h=>h.id!==id);render();toastMsg('Habit deleted ✓')}catch(e){toastMsg(e.message)}};
  window.editGoal=(id)=>{const g=state.goals.find(a=>a.id===id);if(!g)return;editor('Edit goal',`<label>Title<input id="t" class="input" maxlength="100" value="${esc(g.title||g.name)}"></label><label>Description<input id="d" class="input" maxlength="300" value="${esc(g.description||'')}"></label><label>Progress (%)<input id="p" class="input" type="number" min="0" max="100" value="${Number(g.progress||0)}"></label><label>Deadline<input id="dl" class="input" type="date" value="${esc(g.deadline||'')}"></label>`,async x=>{const uid=requireUser(),title=v(x,'t');if(!title)throw new Error('Enter a goal title.');const progress=Math.max(0,Math.min(100,Number(x.querySelector('#p').value)||0));const patch={title,description:v(x,'d')||null,progress,deadline:v(x,'dl')||null,is_completed:progress>=100};const r=await db().from('goals').update(patch).eq('id',id).eq('user_id',uid).select('*').single();fail(r.error,'Unable to update goal');Object.assign(g,patch,{name:title});render();toastMsg('Goal updated ✓')})};
  window.deleteGoal=async(id)=>{if(!confirm('Delete this goal?'))return;try{const uid=requireUser();let r=await db().from('goal_milestones').delete().eq('goal_id',id);if(r.error && !/relation.*does not exist/i.test(r.error.message))fail(r.error,'Unable to delete milestones');r=await db().from('goals').delete().eq('id',id).eq('user_id',uid);fail(r.error,'Unable to delete goal');state.goals=state.goals.filter(g=>g.id!==id);render();toastMsg('Goal deleted ✓')}catch(e){toastMsg(e.message)}};
  window.editStudy=(id)=>{const s=state.study.find(a=>a.id===id);if(!s)return;editor('Edit study session',`<label>Title<input id="t" class="input" maxlength="120" value="${esc(s.title||'Study Session')}"></label><label>Date/time<input id="st" class="input" type="datetime-local" value="${s.started_at?new Date(s.started_at).toISOString().slice(0,16):''}"></label><label>Duration (minutes)<input id="d" class="input" type="number" min="1" max="720" value="${Math.max(1,Number(s.duration_minutes)||1)}"></label><label><input id="c" type="checkbox" ${s.completed?'checked':''}> Completed</label>`,async x=>{const uid=requireUser(),title=v(x,'t')||'Study Session',mins=Math.max(1,Math.min(720,Number(x.querySelector('#d').value)||1)),started=x.querySelector('#st').value?new Date(x.querySelector('#st').value).toISOString():s.started_at,completed=x.querySelector('#c').checked,patch={title,started_at:started,duration_minutes:mins,completed,ended_at:completed&&started?new Date(new Date(started).getTime()+mins*60000).toISOString():null};const r=await db().from('study_sessions').update(patch).eq('id',id).eq('user_id',uid).select('*').single();fail(r.error,'Unable to update study session');Object.assign(s,patch);render();toastMsg('Study session updated ✓')})};
  window.deleteStudy=async(id)=>{if(!confirm('Delete this study session?'))return;try{const uid=requireUser(),r=await db().from('study_sessions').delete().eq('id',id).eq('user_id',uid);fail(r.error,'Unable to delete study session');state.study=state.study.filter(s=>s.id!==id);render();toastMsg('Study session deleted ✓')}catch(e){toastMsg(e.message)}};

  const addActions=()=>{document.querySelectorAll('.qf-row-actions').forEach(a=>a.dataset.ready='1');};
  const oldRender=window.render;window.render=oldRender;
  window.addEventListener('load',()=>setTimeout(addActions,1000));
})();
