(()=>{
  const db=()=>window.supabaseClient;
  const T=(s)=>String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  const uid=async()=>{const {data,error}=await db().auth.getUser();if(error||!data?.user)throw new Error('Your session has expired. Please sign in again.');return data.user.id};
  const modal=(title,body,onSave)=>{
    document.getElementById('qf-editor')?.remove();
    const el=document.createElement('div');el.id='qf-editor';el.className='qf-editor-backdrop';
    el.innerHTML=`<div class="qf-editor-card"><div class="row between"><h3>${T(title)}</h3><button class="btn secondary" id="qf-editor-close">✕</button></div><div class="qf-editor-body">${body}</div><div class="actions qf-editor-actions"><button class="btn secondary" id="qf-editor-cancel">Cancel</button><button class="btn" id="qf-editor-save">Save changes</button></div></div>`;
    document.body.appendChild(el);const close=()=>el.remove();el.querySelector('#qf-editor-close').onclick=close;el.querySelector('#qf-editor-cancel').onclick=close;
    el.querySelector('#qf-editor-save').onclick=async()=>{const b=el.querySelector('#qf-editor-save');b.disabled=true;b.textContent='Saving…';try{await onSave(el);close()}catch(e){console.error(e);toast(e?.message||'Could not save changes');b.disabled=false;b.textContent='Save changes'}};
  };
  const val=(el,id)=>el.querySelector('#'+id)?.value?.trim()||'';
  const fail=(e,what)=>{if(e)throw new Error(`${what}: ${e.message||'Unknown database error'}`)};

  window.addHabit=()=>modal('Create habit',`<label>Habit name<input id="h-name" class="input" maxlength="80" placeholder="e.g. Read 20 minutes"></label><label>Description<input id="h-desc" class="input" maxlength="240" placeholder="Optional"></label><label>Frequency<select id="h-frequency" class="input"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="custom">Custom</option></select></label><label>Target per week<input id="h-target" class="input" type="number" min="1" max="7" value="7"></label><label>Reminder time<input id="h-reminder" class="input" type="time"></label>`,async m=>{
    const name=val(m,'h-name');if(!name)throw new Error('Enter a habit name.');const frequency=val(m,'h-frequency')||'daily';const target=Math.max(1,Math.min(7,Number(m.querySelector('#h-target').value)||7));const reminder=val(m,'h-reminder')||null;const user_id=await uid();
    const {data,error}=await db().from('habits').insert({user_id,name,description:val(m,'h-desc')||null,icon:'check',frequency,target_per_week:target,reminder_time:reminder,is_active:true}).select('*').single();
    fail(error,'Unable to create habit');if(data)state.habits.push({...data,days:[]});render();toast('Habit created ✓');
  });

  window.editHabit=(id)=>{const h=state.habits.find(x=>x.id===id);if(!h)return;modal('Edit habit',`<label>Habit name<input id="h-name" class="input" value="${T(h.name)}" maxlength="80"></label><label>Description<input id="h-desc" class="input" value="${T(h.description||'')}" maxlength="240"></label><label>Frequency<select id="h-frequency" class="input"><option value="daily" ${h.frequency==='daily'?'selected':''}>Daily</option><option value="weekly" ${h.frequency==='weekly'?'selected':''}>Weekly</option><option value="custom" ${h.frequency==='custom'?'selected':''}>Custom</option></select></label><label>Target per week<input id="h-target" class="input" type="number" min="1" max="7" value="${Math.max(1,Math.min(7,Number(h.target_per_week)||7))}"></label><label>Reminder time<input id="h-reminder" class="input" type="time" value="${T(h.reminder_time||'')}"></label>`,async m=>{const name=val(m,'h-name');if(!name)throw new Error('Enter a habit name.');const patch={name,description:val(m,'h-desc')||null,frequency:val(m,'h-frequency')||'daily',target_per_week:Math.max(1,Math.min(7,Number(m.querySelector('#h-target').value)||7)),reminder_time:val(m,'h-reminder')||null,updated_at:new Date().toISOString()};const user_id=await uid();const {error}=await db().from('habits').update(patch).eq('id',id).eq('user_id',user_id);fail(error,'Unable to update habit');Object.assign(h,patch);render();toast('Habit updated ✓')})};
  window.deleteHabit=async(id)=>{if(!confirm('Archive this habit? Your completion history will stay saved.'))return;try{const user_id=await uid();const {error}=await db().from('habits').update({is_active:false,updated_at:new Date().toISOString()}).eq('id',id).eq('user_id',user_id);if(error)throw error;state.habits=state.habits.filter(h=>h.id!==id);render();toast('Habit archived')}catch(e){toast(e.message||'Unable to archive habit')}};
  window.habitRow=(h)=>`<div class="item"><button class="check ${done(h)?'done':''}" onclick="toggleHabit('${h.id}')">${done(h)?'✓':''}</button><div class="grow"><b>${T(h.name)}</b><div class="muted">🔥 ${streak(h)} day streak · ${h.days.length} completions</div></div><span class="pill">${done(h)?'Done':'Today'}</span><div class="qf-row-actions"><button class="icon-btn" title="Edit habit" onclick="editHabit('${h.id}')">✎</button><button class="icon-btn danger" title="Archive habit" onclick="deleteHabit('${h.id}')">⌫</button></div></div>`;

  window.goals=()=>shell(`<div class="top"><div><h2>Goals</h2><div class="muted">Long-term progress powered by daily action.</div></div><button class="btn" onclick="addGoal()">+ Goal</button></div>${state.goals.length?state.goals.map(g=>`<div class="card"><div class="row between"><div><h3>${T(g.name)}</h3><div class="muted">${g.deadline?`Due ${T(g.deadline)}`:'No deadline'}</div></div><div class="qf-row-actions"><b>${Number(g.progress||0)}%</b><button class="icon-btn" title="Edit goal" onclick="editGoal('${g.id}')">✎</button></div></div><div class="bar"><i style="width:${Math.min(100,Number(g.progress||0))}%"></i></div><p class="muted">${T(g.description||'')}</p>${g.milestones?.length?`<div class="list">${g.milestones.map(m=>`<div class="item"><span class="check ${m.is_completed?'done':''}">${m.is_completed?'✓':''}</span><div class="grow">${T(m.title)}</div></div>`).join('')}</div>`:''}</div>`).join(''):'<div class="card"><p class="muted">No goals yet. Add your first goal above.</p></div>'}`);
  window.addGoal=()=>modal('Create goal',`<label>Goal title<input id="g-title" class="input" maxlength="100" placeholder="e.g. Finish mathematics chapter"></label><label>Description<input id="g-desc" class="input" maxlength="300" placeholder="Optional"></label><label>Progress (%)<input id="g-progress" class="input" type="number" min="0" max="100" value="0"></label><label>Deadline<input id="g-deadline" class="input" type="date"></label>`,async m=>{const title=val(m,'g-title');if(!title)throw new Error('Enter a goal title.');const progress=Math.max(0,Math.min(100,Number(m.querySelector('#g-progress').value)||0));const user_id=await uid();const {data,error}=await db().from('goals').insert({user_id,title,description:val(m,'g-desc')||null,progress,deadline:val(m,'g-deadline')||null,is_completed:progress>=100}).select('*').single();fail(error,'Unable to create goal');if(data)state.goals.push({...data,name:data.title,milestones:[]});render();toast('Goal created ✓')});
  window.editGoal=(id)=>{const g=state.goals.find(x=>x.id===id);if(!g)return;modal('Edit goal',`<label>Goal title<input id="g-title" class="input" maxlength="100" value="${T(g.title||g.name)}"></label><label>Description<input id="g-desc" class="input" maxlength="300" value="${T(g.description||'')}"></label><label>Progress (%)<input id="g-progress" class="input" type="number" min="0" max="100" value="${Number(g.progress||0)}"></label><label>Deadline<input id="g-deadline" class="input" type="date" value="${T(g.deadline||'')}"></label>`,async m=>{const title=val(m,'g-title');if(!title)throw new Error('Enter a goal title.');const progress=Math.max(0,Math.min(100,Number(m.querySelector('#g-progress').value)||0));const patch={title,description:val(m,'g-desc')||null,progress,deadline:val(m,'g-deadline')||null,is_completed:progress>=100,updated_at:new Date().toISOString()};const user_id=await uid();const {error}=await db().from('goals').update(patch).eq('id',id).eq('user_id',user_id);fail(error,'Unable to update goal');Object.assign(g,patch,{name:title});render();toast('Goal updated ✓')})};

  window.study=()=>shell(`<div class="top"><div><h2>Study Planner</h2><div class="muted">Plan sessions, record focus time and edit your study history.</div></div><button class="btn" onclick="addStudy()">+ Session</button></div><div class="grid"><div class="card metric"><div class="muted">Total time</div><strong>${Math.round(totalStudy())}m</strong></div><div class="card metric"><div class="muted">Sessions</div><strong>${state.study.length}</strong></div></div><div class="card"><h3>⏱️ Custom Focus</h3><div class="muted">Choose a focus duration or enter your own 1–180 minutes.</div><div class="actions" style="flex-wrap:wrap;margin-top:12px"><button class="btn secondary" onclick="setTimerMinutes(15)">15m</button><button class="btn secondary" onclick="setTimerMinutes(25)">25m</button><button class="btn secondary" onclick="setTimerMinutes(45)">45m</button><button class="btn secondary" onclick="setTimerMinutes(60)">60m</button><input id="customTimer" class="input" type="number" min="1" max="180" value="${Math.round(timerTotal/60)}" style="max-width:110px"><button class="btn" onclick="setTimerMinutes(document.getElementById('customTimer').value)">Set</button></div><div class="timer" id="timer">${fmtTimer()}</div><div class="actions"><button class="btn" onclick="startTimer()">${timer?'Pause':'Start'}</button><button class="btn secondary" onclick="resetTimer()">Reset</button></div></div><div class="card"><h3>Study history</h3><div class="list">${state.study.length?state.study.slice(0,30).map(s=>`<div class="item"><div class="grow"><b>${T(s.title||'Study Session')}</b><div class="muted">${s.started_at?new Date(s.started_at).toLocaleString():'Today'} · ${Number(s.duration_minutes)||0} min</div></div><span class="pill green">${s.completed?'Completed':'Planned'}</span><div class="qf-row-actions"><button class="icon-btn" title="Edit session" onclick="editStudy('${s.id}')">✎</button><button class="icon-btn danger" title="Delete session" onclick="deleteStudy('${s.id}')">⌫</button></div></div>`).join(''):'<p class="muted">No study sessions yet.</p>'}</div></div>`);
  window.addStudy=()=>modal('Create study session',`<label>Session title<input id="s-title" class="input" maxlength="120" placeholder="e.g. Physics revision"></label><label>Date/time<input id="s-start" class="input" type="datetime-local" value="${new Date().toISOString().slice(0,16)}"></label><label>Duration (minutes)<input id="s-duration" class="input" type="number" min="1" max="720" value="25"></label><label class="qf-check-label"><input id="s-completed" type="checkbox"> Mark as completed</label>`,async m=>{const title=val(m,'s-title')||'Study Session';const mins=Math.max(1,Math.min(720,Number(m.querySelector('#s-duration').value)||25));const started=m.querySelector('#s-start').value?new Date(m.querySelector('#s-start').value).toISOString():new Date().toISOString();const completed=m.querySelector('#s-completed').checked;const user_id=await uid();const {data,error}=await db().from('study_sessions').insert({user_id,title,started_at:started,duration_minutes:mins,completed,ended_at:completed?new Date(new Date(started).getTime()+mins*60000).toISOString():null}).select('*').single();fail(error,'Unable to create study session');if(data)state.study.unshift(data);render();toast('Study session created ✓')});
  window.editStudy=(id)=>{const s=state.study.find(x=>x.id===id);if(!s)return;modal('Edit study session',`<label>Session title<input id="s-title" class="input" maxlength="120" value="${T(s.title||'Study Session')}"></label><label>Date/time<input id="s-start" class="input" type="datetime-local" value="${s.started_at?new Date(s.started_at).toISOString().slice(0,16):new Date().toISOString().slice(0,16)}"></label><label>Duration (minutes)<input id="s-duration" class="input" type="number" min="1" max="720" value="${Math.max(1,Number(s.duration_minutes)||1)}"></label><label class="qf-check-label"><input id="s-completed" type="checkbox" ${s.completed?'checked':''}> Completed</label>`,async m=>{const title=val(m,'s-title')||'Study Session';const mins=Math.max(1,Math.min(720,Number(m.querySelector('#s-duration').value)||1));const started=m.querySelector('#s-start').value?new Date(m.querySelector('#s-start').value).toISOString():s.started_at;const completed=m.querySelector('#s-completed').checked;const patch={title,started_at:started,duration_minutes:mins,completed,ended_at:completed&&started?new Date(new Date(started).getTime()+mins*60000).toISOString():null};const user_id=await uid();const {error}=await db().from('study_sessions').update(patch).eq('id',id).eq('user_id',user_id);fail(error,'Unable to update study session');Object.assign(s,patch);render();toast('Study session updated ✓')})};
  window.deleteStudy=async(id)=>{if(!confirm('Delete this study session?'))return;try{const user_id=await uid();const {error}=await db().from('study_sessions').delete().eq('id',id).eq('user_id',user_id);if(error)throw error;state.study=state.study.filter(s=>s.id!==id);render();toast('Study session deleted')}catch(e){toast(e.message||'Unable to delete session')}};
})();
