/* QuantumFlow Groups: public/private groups, invites, members, challenges, announcements. */
(function(){
  const wait=()=>{if(!window.state||typeof window.render!=='function'||!window.supabaseClient||!window.shell){setTimeout(wait,100);return;}
    const baseRender=window.render; let selected=null; let section='discover';
    const nav=()=>{const el=document.getElementById('nav');if(!el)return;const tabs=[['home','⌂','Home'],['habits','✓','Habits'],['study','▣','Study'],['progress','◒','Progress'],['goals','◆','Goals'],['groups','👥','Groups'],['leaderboard','🏆','Rank'],['profile','●','Profile']];el.innerHTML=tabs.map(x=>`<button class="${window.state.tab===x[0]?'active':''}" onclick="state.tab='${x[0]}';window.qfGroupSelected=null;window.qfGroupSection='discover';render()"><b>${x[1]}</b>${x[2]}</button>`).join('');};
    window.qfGroupSelected=null; window.qfGroupSection='discover';
    const esc=window.esc||((s)=>String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[m])));
    const toast=(m)=>window.showToast?window.showToast(m):alert(m);
    const initials=(n)=>String(n||'Q').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
    async function current(){let u=window.currentUser;if(!u){const r=await window.supabaseClient.auth.getUser();u=r.data?.user;}return u;}
    async function loadGroups(){const u=await current();if(!u)return {mine:[],publics:[]};const mine=await window.supabaseClient.from('group_members').select('group_id,role,status,groups(id,name,description,visibility,join_mode,icon,owner_id,invite_code,created_at)').eq('user_id',u.id).eq('status','active');const publics=await window.supabaseClient.from('groups').select('id,name,description,visibility,join_mode,icon,owner_id,created_at').eq('visibility','public').order('created_at',{ascending:false}).limit(30);return {mine:(mine.data||[]).map(x=>({...x.groups,member_role:x.role})).filter(Boolean),publics:publics.data||[]};}
    function groupCard(g,joined){return `<div class="card group-card" onclick="window.qfOpenGroup('${g.id}')"><div class="actions"><div class="group-icon">${esc(g.icon||'👥')}</div><div class="grow"><h3 style="margin:3px 0">${esc(g.name)}</h3><div class="muted">${esc(g.description||'A QuantumFlow community.')}</div></div></div><div class="group-meta"><span class="pill">${g.visibility==='private'?'🔐 Private':'🌍 Public'}</span><span class="pill">${g.join_mode==='open'?'Open':g.join_mode==='approval'?'Approval':'Invite only'}</span>${joined?'<span class="pill green">✓ Joined</span>':''}</div></div>`;}
    async function renderGroups(){const {mine,publics}=await loadGroups();if(selected){return await renderDetail(selected);}
      const discover=window.qfGroupSection==='discover'; const list=discover?publics:mine; return window.shell(`<div class="qf-groups-shell"><div class="top"><div><div class="badge">⚛️ COMMUNITY</div><h2>👥 Groups</h2><div class="muted">Build consistency together without exposing private personal data.</div></div></div><div class="group-tabs"><button class="btn ${discover?'':'secondary'}" onclick="window.qfGroupSection='discover';render()">🌍 Discover</button><button class="btn ${!discover?'':'secondary'}" onclick="window.qfGroupSection='mine';render()">⭐ My Groups</button><button class="btn secondary" onclick="window.qfCreateGroup()">＋ Create</button><button class="btn secondary" onclick="window.qfJoinInvite()">🔑 Join Code</button></div>${!discover&&mine.length===0?`<div class="card group-empty"><div class="emoji">👥</div><h3>No groups yet</h3><p class="muted">Create your own community or join one with an invite code.</p></div>`:''}<div class="group-grid">${list.map(g=>groupCard(g,!discover&&mine.some(m=>m.id===g.id))).join('')}</div>${discover?`<div class="card"><h3>🔐 Private groups</h3><p class="muted">Private groups are not publicly listed. Join them using an invite code shared by the owner.</p></div>`:''}</div>`,'Groups');}
    async function renderDetail(id){const u=await current();const {data:g,error}=await window.supabaseClient.from('groups').select('*').eq('id',id).single();if(error||!g){selected=null;return renderGroups();}const mem=await window.supabaseClient.rpc('group_members_public',{p_group_id:id});const board=await window.supabaseClient.rpc('group_leaderboard',{p_group_id:id});const ch=await window.supabaseClient.from('group_challenges').select('*').eq('group_id',id).order('end_date',{ascending:true});const ann=await window.supabaseClient.from('group_announcements').select('*').eq('group_id',id).order('created_at',{ascending:false}).limit(10);const mine=(mem.data||[]).find(x=>x.user_id===u?.id);const isAdmin=['owner','admin','moderator'].includes(mine?.role);const tabs=['overview','leaderboard','members','challenges'];const active=window.qfGroupSection==='detailBoard'?'leaderboard':window.qfGroupSection==='detailMembers'?'members':window.qfGroupSection==='detailChallenges'?'challenges':'overview';
      let body=''; if(active==='leaderboard'){body=`<div class="card"><h3>🏆 Group Leaderboard</h3>${(board.data||[]).map(r=>`<div class="rank-row"><strong>${r.rank<=3?['🥇','🥈','🥉'][r.rank-1]:'#'+r.rank}</strong><div><b>${esc(r.display_name)}</b><div class="muted">Consistency matters more than perfection.</div></div><b class="color-goal">⚡ ${r.xp}</b></div>`).join('')||'<p class="muted">No ranked members yet.</p>'}</div>`;} else if(active==='members'){body=`<div class="card"><h3>👥 Members · ${(mem.data||[]).length}</h3>${(mem.data||[]).map(m=>`<div class="member-row"><div class="avatar">${initials(m.display_name)}</div><div class="grow"><b>${esc(m.display_name)}</b><div class="muted">${esc(m.role)}</div></div></div>`).join('')}</div>`;} else if(active==='challenges'){body=`<div class="card"><div class="top"><div><h3>🔥 Challenges</h3><div class="muted">Turn consistency into shared momentum.</div></div>${isAdmin?'<button class="btn" onclick="window.qfCreateChallenge(\''+id+'\')">＋ Challenge</button>':''}</div>${(ch.data||[]).map(c=>`<div class="card challenge-card"><h3>${esc(c.title)}</h3><p class="muted">${esc(c.description)}</p><div class="muted">Target ${c.target} · +${c.reward_xp} XP · ends ${esc(c.end_date)}</div><div class="bar"><i style="width:0%"></i></div><div class="challenge-actions"><button class="btn secondary" onclick="window.qfProgressChallenge('${c.id}',${c.target},'${id}')">+ Progress</button></div></div>`).join('')||'<p class="muted">No challenges yet.</p>'}</div>`;} else {body=`<div class="card"><h3>📣 Announcements</h3>${(ann.data||[]).map(a=>`<div class="item"><div class="grow"><b>${esc(a.content)}</b><div class="muted">${new Date(a.created_at).toLocaleString()}</div></div></div>`).join('')||'<p class="muted">No announcements yet.</p>'}</div>${isAdmin?`<div class="card"><h3>📣 Post announcement</h3><textarea id="qfAnn" maxlength="1000" placeholder="Share an update with the group…"></textarea><button class="btn" onclick="window.qfPostAnnouncement('${id}')">Post</button></div>`:''}<div class="card"><h3>🔐 Privacy</h3><p class="muted">Your personal habit and goal names stay private. Group activity only exposes information intentionally shared with the group.</p></div>`;}
      return window.shell(`<div class="qf-groups-shell"><div class="top"><button class="btn secondary" onclick="window.qfBackGroups()">← Groups</button><div class="actions"><button class="btn secondary" onclick="window.qfInvite('${esc(g.invite_code||'')}')">🔑 Invite</button></div></div><div class="card group-hero"><div class="actions"><div class="group-icon">${esc(g.icon)}</div><div class="grow"><div class="badge">${g.visibility==='private'?'🔐 PRIVATE':'🌍 PUBLIC'}</div><h2 style="margin:8px 0 4px">${esc(g.name)}</h2><p class="muted">${esc(g.description||'')}</p></div></div>${g.visibility==='private'?`<div class="pill group-code" style="margin-top:12px">Invite code: ${esc(g.invite_code||'—')}</div>`:''}</div><div class="group-tabs">${tabs.map((t,i)=>`<button class="btn ${active===t?'':'secondary'}" onclick="window.qfGroupSection='${t==='leaderboard'?'detailBoard':t==='members'?'detailMembers':t==='challenges'?'detailChallenges':'detail'}';render()">${['Overview','Leaderboard','Members','Challenges'][i]}</button>`).join('')}</div>${body}</div>`,'Group');}
    window.qfOpenGroup=(id)=>{selected=id;window.qfGroupSelected=id;window.qfGroupSection='detail';state.tab='groups';render();};
    window.qfBackGroups=()=>{selected=null;window.qfGroupSelected=null;window.qfGroupSection='discover';render();};
    window.qfCreateGroup=async()=>{const name=prompt('Group name');if(!name)return;const desc=prompt('Short description')||'';const privateGroup=confirm('Make this group PRIVATE?\nOK = Private\nCancel = Public');let mode='open';if(privateGroup){const inviteOnly=confirm('Make it invite-only?\nOK = Invite only\nCancel = Approval required');mode=inviteOnly?'invite':'approval';}const icon=prompt('Choose an emoji/icon','👥')||'👥';const {data,error}=await window.supabaseClient.rpc('create_group',{p_name:name,p_description:desc,p_visibility:privateGroup?'private':'public',p_join_mode:mode,p_icon:icon});if(error)return toast(error.message);toast('✨ Group created');window.qfOpenGroup(data);};
    window.qfJoinInvite=async()=>{const code=prompt('Enter group invite code');if(!code)return;const {data,error}=await window.supabaseClient.rpc('join_group_by_invite',{p_code:code});if(error)return toast(error.message);toast('🎉 Joined group');window.qfOpenGroup(data);};
    window.qfInvite=(code)=>{if(!code)return toast('This group has no invite code');const text=`Join my QuantumFlow group with code ${code}`;navigator.clipboard?.writeText(text).then(()=>toast('🔑 Invite copied')).catch(()=>prompt('Copy this invite code',code));};
    window.qfCreateChallenge=async(id)=>{const title=prompt('Challenge title');if(!title)return;const desc=prompt('Description')||'';const target=Math.max(1,Number(prompt('Target number', '5'))||5);const reward=Math.max(0,Number(prompt('Reward XP','100'))||100);const days=Math.max(1,Number(prompt('Duration in days','7'))||7);const end=new Date(Date.now()+days*86400000).toISOString().slice(0,10);const u=await current();const {error}=await window.supabaseClient.from('group_challenges').insert({group_id:id,title,description:desc,target,reward_xp:reward,end_date:end,created_by:u.id});if(error)return toast(error.message);toast('🔥 Challenge created');render();};
    window.qfProgressChallenge=async(cid,target,gid)=>{const u=await current();const q=await window.supabaseClient.from('group_challenge_progress').select('progress').eq('challenge_id',cid).eq('user_id',u.id).maybeSingle();const next=Math.min(target,(q.data?.progress||0)+1);const {error}=await window.supabaseClient.from('group_challenge_progress').upsert({challenge_id:cid,user_id:u.id,progress:next,completed:next>=target,updated_at:new Date().toISOString()});if(error)return toast(error.message);toast(next>=target?'🏆 Challenge complete!':'⚡ Progress saved');render();};
    window.qfPostAnnouncement=async(id)=>{const el=document.getElementById('qfAnn');const content=el?.value?.trim();if(!content)return toast('Write an announcement first');const u=await current();const {error}=await window.supabaseClient.from('group_announcements').insert({group_id:id,author_id:u.id,content});if(error)return toast(error.message);toast('📣 Posted');render();};
    window.render=async function(){if(window.state?.tab==='groups'){nav();const app=document.getElementById('app');if(app)app.innerHTML='<div class="wrap"><div class="card"><p class="muted">Loading Groups…</p></div></div>';const html=await renderGroups();if(app)app.innerHTML=html;nav();return;}baseRender();nav();};
    nav();
  };wait();
})();