/* Quantum Flow offline data layer */
(function(){'use strict';
const DB='quantum-flow-offline',VER=1,STORE='kv',QUEUE='queue';let db,ready;
function open(){if(ready)return ready;ready=new Promise((res,rej)=>{const r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE);if(!d.objectStoreNames.contains(QUEUE)){const s=d.createObjectStore(QUEUE,{keyPath:'id',autoIncrement:true});s.createIndex('createdAt','createdAt')}};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)});return ready}
function tx(store,mode,fn){return open().then(d=>new Promise((res,rej)=>{const t=d.transaction(store,mode),s=t.objectStore(store);let out;try{out=fn(s)}catch(e){rej(e);return}t.oncomplete=()=>res(out);t.onerror=()=>rej(t.error)}))}
const api={async set(key,value){return tx(STORE,'readwrite',s=>s.put({value,updatedAt:Date.now()},key))},async get(key){return tx(STORE,'readonly',s=>new Promise((res,rej)=>{const r=s.get(key);r.onsuccess=()=>res(r.result?.value??null);r.onerror=()=>rej(r.error)}))},async remove(key){return tx(STORE,'readwrite',s=>s.delete(key))},async queue(op){return tx(QUEUE,'readwrite',s=>s.add({...op,createdAt:Date.now()}))},async allQueue(){return tx(QUEUE,'readonly',s=>new Promise((res,rej)=>{const a=[],r=s.openCursor();r.onsuccess=()=>{const c=r.result;if(!c)return res(a);a.push(c.value);c.continue()};r.onerror=()=>rej(r.error)}))},async done(id){return tx(QUEUE,'readwrite',s=>s.delete(id))}};
function status(online){document.documentElement.classList.toggle('qf-offline',!online);let el=document.getElementById('qf-offline-indicator');if(!el){el=document.createElement('div');el.id='qf-offline-indicator';el.setAttribute('role','status');document.body.appendChild(el)}el.textContent=online?'● Online':'● Offline — changes saved locally';el.dataset.online=online?'1':'0'}
async function sync(){if(!navigator.onLine)return;const items=await api.allQueue();if(!items.length){status(true);return}let failed=false;for(const item of items){try{if(typeof window.qfOfflineApply==='function')await window.qfOfflineApply(item);else{failed=true;break}await api.done(item.id)}catch(e){failed=true;console.warn('Offline sync failed',e)}}status(true);if(!failed&&items.length)window.dispatchEvent(new CustomEvent('qf:sync-complete',{detail:{count:items.length}}))}
window.QFOffline=api;window.qfOfflineQueue=api.queue;window.qfOfflineSync=sync;
window.addEventListener('online',()=>{status(true);sync()});window.addEventListener('offline',()=>status(false));
open().then(()=>status(navigator.onLine));setInterval(sync,30000);
})();